version: '3.3'

services:
  redis:
    image: redis:6.2-alpine
    restart: on-failure
    command : redis-server
    env_file:
      - ".env"
    ports:
      - "6379:6380"
  bot:
    build: .
    stop_signal: SIGINT
    command: python3 -m bot
    restart: always
    env_file:
      - ".env"
    depends_on:
      - redis

    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"